apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: mad-pgcluster
spec:
  services: 
    - group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster 
      name: hippo
  application: 
    name: devspaces
    group: apps
    version: v1
    resource: deployments



